name: Issue Notifier

on:
  issues:
    types: [opened]

permissions:
  issues: read

jobs:
  notify:
    name: "Telegram notification"
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram notification for new issue
        uses: sehat1137/telegram-notifier@v1.0.0
        with:
          tg-bot-token: ${{ secrets.TELEGRAM_TOKEN }}
          tg-chat-id: ${{ secrets.TELEGRAM_TO }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
